---
window:
  decorations: full
  startup_mode: Maximized
font:
  normal:
    family: 'MesloLGS NF'
    style: Regular
#  bold:
#    family: 'MesloLGS Nerd Font Mono'
#    style: Bold
#  italic:
#    family: 'MesloLGS Nerd Font Mono'
#    style: Italic
#  bold_italic:
#    family: 'MesloLGS Nerd Font Mono'
#    style: Bold Italic
  size: 11
background_opacity: 1.0
# Live config reload (changes require restart)
live_config_reload: true
# https://github.com/alacritty/alacritty/wiki/Color-schemes
schemes:
  solarized_dark: &dark
    # Default colors
    primary:
      background: '#002b36'  # base03
      foreground: '#839496'  # base0
    # Cursor colors
    cursor:
      text:   '#002b36'  # base03
      cursor: '#839496'  # base0
    # Normal colors
    normal:
      black:   '#073642'  # base02
      red:     '#dc322f'  # red
      green:   '#859900'  # green
      yellow:  '#b58900'  # yellow
      blue:    '#268bd2'  # blue
      magenta: '#d33682'  # magenta
      cyan:    '#2aa198'  # cyan
      white:   '#eee8d5'  # base2
    # Bright colors
    bright:
      black:   '#002b36'  # base03
      red:     '#cb4b16'  # orange
      green:   '#586e75'  # base01
      yellow:  '#657b83'  # base00
      blue:    '#839496'  # base0
      magenta: '#6c71c4'  # violet
      cyan:    '#93a1a1'  # base1
      white:   '#fdf6e3'  # base3
  solarized_light: &light
    primary:
      background: '#fdf6e3'  # base3
      foreground: '#657b83'  # base00
    # Cursor colors
    cursor:
      text:   '#fdf6e3'  # base3
      cursor: '#657b83'  # base00
    # Normal colors
    normal:
      black:   '#073642'  # base02
      red:     '#dc322f'  # red
      green:   '#859900'  # green
      yellow:  '#b58900'  # yellow
      blue:    '#268bd2'  # blue
      magenta: '#d33682'  # magenta
      cyan:    '#2aa198'  # cyan
      white:   '#eee8d5'  # base2
    # Bright colors
    bright:
      black:   '#002b36'  # base03
      red:     '#cb4b16'  # orange
      green:   '#586e75'  # base01
      yellow:  '#657b83'  # base00
      blue:    '#839496'  # base0
      magenta: '#6c71c4'  # violet
      cyan:    '#93a1a1'  # base1
      white:   '#fdf6e3'  # base3
  kitty: &kitty
    primary:
      background: '#000000'
      foreground: '#dddddd'
    # Normal colors
    normal:
      black:   '#000000'
      red:     '#cc0403'
      green:   '#19cb00'
      yellow:  '#cecb00'
      blue:    '#0d73cc'
      magenta: '#cb1ed1'
      cyan:    '#0dcdcd'
      white:   '#dddddd'
    # Bright colors
    bright:
      black:   '#767676'
      red:     '#f2201f'
      green:   '#23fd00'
      yellow:  '#fffd00'
      blue:    '#1a8fff'
      magenta: '#fd28ff'
      cyan:    '#14ffff'
      white:   '#ffffff'
colors: *kitty
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true
# Allow # in vim
key_bindings:
  - { key: Key3,     mods: Alt,     chars: "#"                           }
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Scrolling distance multiplier.
  multiplier: 3

  # Faux Scrolling
  #
  # The `faux_multiplier` setting controls the number
  # of lines the terminal should scroll when the alternate
  # screen buffer is active. This is used to allow mouse
  # scrolling for applications like `man`.
  #
  # To disable this completely, set `faux_multiplier` to 0.
  faux_multiplier: 3

  # Automatically scroll to the bottom when new text is written
  # to the terminal.
  auto_scroll: false

use_thin_strokes: true

